// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import ()

type Bot struct {
	ID             int64
	Username       string
	Passwd         string
	SharedSecret   string
	IdentitySecret string
	ApiKey         string
}

type Item struct {
	ID         int64
	BotID      int64
	AppID      int64
	AssetID    int64
	ClassID    int64
	InstanceID int64
}
