// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package database

import ()

type Inventory struct {
	ID         int64
	BotID      int64
	AppID      int64
	AssetID    int64
	ClassID    int64
	InstanceID int64
}
